# Generated by Django 4.0.4 on 2022-07-02 17:06

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('number_of_rooms', models.IntegerField(null=True)),
                ('Date_in', models.DateField(null=True)),
                ('Date_out', models.DateField(null=True)),
                ('book_price', models.FloatField(null=True)),
                ('booking_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'single'), ('double ', 'double'), ('premium', 'premium')], default='single', max_length=9)),
                ('number', models.IntegerField()),
                ('price_per_night', models.FloatField()),
                ('amenities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default=hotel.models.room_num_generator, max_length=10, unique=True)),
                ('book_status', models.BooleanField(default=False)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomcategory', to='hotel.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Checkings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('checkout_date', models.DateTimeField()),
                ('check_out_status', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.booking')),
                ('checkin_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinroom', to='hotel.room')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
    ]
