# Generated by Django 4.0.4 on 2022-07-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='checkings',
            name='check_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='checkings',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.booking'),
        ),
        migrations.AlterField(
            model_name='checkings',
            name='check_out_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
