# Generated by Django 4.0.4 on 2022-07-04 14:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_check_in_status_checkings_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
