# Generated by Django 4.0.4 on 2022-07-04 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_roomtype_image1_roomtype_image2_roomtype_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
