# Generated by Django 4.0.4 on 2022-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkings',
            name='check_out_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
