# Generated by Django 4.0.4 on 2022-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_checkings_check_out_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkings',
            name='checkin_room',
            field=models.CharField(max_length=100),
        ),
    ]
